spring:
  application:
    name: demo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/demo}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:demo}
    password: ${DB_PASSWORD:demo}
  exposed:
    generate-ddl: false
  flyway:
    locations: classpath:db/migration
