CREATE TABLE IF NOT EXISTS passenger (id BIGSERIAL PRIMARY KEY, "name" TEXT NOT NULL, email TEXT NOT NULL);
ALTER TABLE passenger ADD CONSTRAINT passenger_email_unique UNIQUE (email);
CREATE TABLE IF NOT EXISTS driver (id BIGSERIAL PRIMARY KEY, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL);
CREATE TABLE IF NOT EXISTS taxi (id BIGSERIAL PRIMARY KEY, make_and_model JSON NOT NULL, car_color VARCHAR(50) NOT NULL, driver_id BIGINT NOT NULL, CONSTRAINT fk_taxi_driver_id__id FOREIGN KEY (driver_id) REFERENCES driver(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS taxi_ride (id BIGSERIAL PRIMARY KEY, passenger_id BIGINT NOT NULL, taxi_id BIGINT NOT NULL, pickup_location TEXT NOT NULL, amount DECIMAL(13, 2) NOT NULL, currency VARCHAR(3) NOT NULL, status INT DEFAULT 0 NOT NULL, CONSTRAINT fk_taxi_ride_passenger_id__id FOREIGN KEY (passenger_id) REFERENCES passenger(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_taxi_ride_taxi_id__id FOREIGN KEY (taxi_id) REFERENCES taxi(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE SEQUENCE IF NOT EXISTS taxi_ride_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS passenger_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS driver_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
CREATE SEQUENCE IF NOT EXISTS taxi_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;